apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-db
  template:
    metadata:
      labels:
        app: spotify-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: spotifydb
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: localhost
spec:
  selector:
    app: spotify-db
  ports:
  - port: 5432
    targetPort: 5432